name: pcilabs firmware CI

on:
  push: 
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    
    steps:
    - name: setup qmk
      uses: actions/checkout@master
    - name: compile firmware for all keyboards
      run: |
        qmk mass-compile -j0 -f "manufacturer=PCI Labs"
      
