name: pcilabs firmware CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    
    steps:
    - name: disable safe.directory check
      run: git config --global --add safe.directory '*'
    - name: setup qmk
      uses: actions/checkout@master
    - name: deploy submodules
      run: qmk git-submodule -f
    - name: compile firmware for all keyboards
      continue-on-error: true
      run: qmk mass-compile -j0 -f "manufacturer=PCI Labs" || touch .failed
    - name: upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{github.base_ref || github.ref_name}}
        if-no-files-found: ignore
        path: |
            *.bin
            *.hex
            *.uf2
            .build/failed.*
            .failed
      
